---
# .about.yml project metadata
#
# Copy this template into your project repository's root directory as
# .about.yml and fill in the fields as described below.

# This is a short name of your project that can be used as a URL slug.
# (required)
#name: mage-server

# This is the display name of your project. (required)
full_name: Mage Server

# What is the problem your project solves? What is the solution? Use the
# format shown below. The #dashboard team will gladly help you put this
# together for your project. (required)
description: the Magish Serverish thingermabob

# What is the measurable impact of your project? Use the format shown below.
# The #dashboard team will gladly help you put this together for your project.
# (required)
impact: high

# What kind of team owns the repository? (required)
# values: guild, working-group, project
owner_type: project

# What is your project's current status? (required)
# values: discovery, alpha, beta, live
stage: alpha

# Should this repo have automated tests? If so, set to `true`. (required)
# values: true, false
testable: true

# What are the licenses that apply to the project and/or its components?
# (required)
# Items by property name pattern:
#   .*:
#     name: Name of the license from the Software Package Data Exchange (SPDX): https://spdx.org/licenses/
#     url: URL for the text of the license
licenses:
  mage-server:
    name: CC0
    url: https://github.com/ion-channel/mage-server/blob/master/LICENSE.md

team:
#- github: fred
#  role: lead
